---
- hosts: UAT
  tasks:
    - name: install the latest httpd server
      become: yes
      yum:
        name: httpd
        state: latest
    - name: copy index.html
      become: yes
      copy:
        src: index.html
        dest: /var/www/html
    - name: copy httpd.conf
      become: yes
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
    - name: httpd service start
      become: yes
      service:
        name: httpd
        state: started
